# Build stage
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

# Install all dependencies (including dev)
RUN npm ci

COPY . .

# Run the build command
RUN npm run build


# Production stage
FROM nginx:alpine AS production

WORKDIR /app

# Copy built files from the build stage
COPY --from=builder /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80


ENV NODE_ENV=production

# Command to run nginx
CMD ["nginx", "-g", "daemon off;"]