services:
    frontend:
        image: restaurant-frontend-dev
        build:
            context: ./frontend
            dockerfile: docker/Dockerfile.dev
        container_name: frontend-container-dev
        ports:
            - 5000:5000
        restart: always
        env_file:
            - ./frontend/.env
        volumes:
            - ./frontend:/app
            - /app/node_modules
        depends_on:
            - backend
        networks:
            - restaurant_network
    backend:
        image: restaurant-backend-dev
        build:
            context: ./backend
            dockerfile: docker/Dockerfile.dev
        container_name: backend-container-dev
        ports:
            - 3000:3000
        restart: always
        env_file:
            - ./backend/.env.development
        volumes:
            - ./backend:/app
            - /app/node_modules
        networks:
            - restaurant_network


networks:
  restaurant_network:
    driver: bridge