# Build stage
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

# Install all dependencies (including dev)
RUN npm ci

COPY . .

# Run the build command
RUN npm run build


# Production stage
FROM node:20-alpine AS production

WORKDIR /app

COPY package*.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Copy built files from the build stage
COPY --from=builder /app/build ./build

EXPOSE 3000

CMD [ "npm", "start" ]