#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


# Navigate to the backend folder
cd backend

# Run tests
npm run test

if [ $? -ne 0 ]; then
  echo "Tests failed! Aborting push."
  exit 1
fi

# Go back to the project root
cd ..

# Get the current branch
current_branch=$(git symbolic-ref --short HEAD)

# Check if the branch is master
if [ "$current_branch" = "master" ]; then
  echo "You cannot push to the 'master' branch directly. Please push to a different branch."
  exit 1
fi

exit 0