#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "⏳ Running linting and formatting for staged files..."
# Run lint-staged to lint and format the files
npx lint-staged || {
  echo "❌ Linting or formatting failed. Please fix the issues before proceeding.";
  exit 1;
}

echo "✅ Linting and formatting completed."

# echo "⏳ Checking if linting/formatting modified any files..."
# # Check if any files have been modified by lint-staged
# git diff --cached --exit-code -- 'frontend/**/*.{ts,tsx}' 'backend/**/*.ts' || {
#   echo "❌ Linting/formatting modified files. Please review the changes and re-add them before committing.";
#   exit 1;
# }

# echo "✅ No unexpected changes detected."

echo "⏳ Building the project..."
# Build the project
npm run build-all || {
  echo "❌ Build failed. Please resolve the issues above and try committing again.";
  exit 1;
}

echo "✅ Build completed successfully!"

# If everything is okay, exit with success
exit 0
