name: Build and Push Docker Images

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build backend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME_BACKEND_PROD }} -f ./backend/docker/Dockerfile.prod ./backend
    - name: Push backend Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME_BACKEND_PROD }}

    - name: Build frontend Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME_FRONTEND_PROD }} -f ./frontend/docker/Dockerfile.prod ./frontend
    - name: Push frontend Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME_FRONTEND_PROD }}
